### ISSUE TITLE
User agent for Cloogle

### ISSUE THREAD

**Issue by camilstaps** [W95Psp/CleanForVSCode#2]
Nice to see that you're integrating Cloogle. If you add a specific user agent to the HTTP requests, we can show separate stats on https://cloogle.org/stats/longterm.html (click on 'Operating Systems' or 'Search types per OS'). Currently the user agent is empty.

The current 'special' user agents are [`CloogleBot`](https://github.com/clean-cloogle/CloogleBot), [`cloogle-cli`](https://github.com/clean-cloogle/cloogle-cli), [`CloogleMail`](https://github.com/clean-cloogle/Cloogle-mail), [`cloogle-irc`](https://github.com/clean-cloogle/clean-irc) and [`Clean/libcloogle`](https://github.com/clean-cloogle/libcloogle) so you could choose something similar. If you decide to do this, please let me know what you have chosen and I can update the statistics page.

**Comment by W95Psp** [comment]
Thanks for the feedback, that's nice!
Yes, so I've just added a custom UA, "clean-vscode" :)

**Comment by camilstaps** [comment]
Thanks, I've added it to the stats!
