### ISSUE TITLE
Syntax higlighting does not work for over 6 months now.

### ISSUE THREAD

**Issue by Hossam-Abdin** [W95Psp/CleanForVSCode#6]
First of all, thank you so much for this awesome work. I am using the clean as the language for the course at my university and as I am using Vscode as my text editor while teaching in class I think it would be very helpful to have syntax highlighting so I would appreciate that so much. Also, the extension is not on the market right now so I had to download it manually this time. I am one of many people who are using this extension and it would really help to have this feature. Thanks so much

**Comment by W95Psp** [comment]
Hi, sorry for not answering, I'm not using this extension any longer, so I've postponed infinitely looking into this issue.
But happily @ErinvanderVeen fixed it with PR #7 (merged in master) 🎉
